name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Triggers the action on push events to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner.

    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so the job can access it.

    - name: Install dependencies
      run: npm install  # Installs project dependencies.

    - name: Build the project
      run: npm run build  # Builds your project.

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod  # Deploys the project to Vercel.
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
